export enum GITHUB_ACTIONS {
  GITHUB_REQUEST_START = 'GITHUB_REQUEST_START',
  GITHUB_REQUEST_END = 'GITHUB_REQUEST_END',
  GITHUB_REQUEST_USERS = 'GITHUB_REQUEST_USERS',
  GITHUB_REQUEST_USER = 'GITHUB_REQUEST_USER',
  GITHUB_REQUEST_USER_REPOS = 'GITHUB_REQUEST_USER_REPOS',
  GITHUB_REQUEST_ERROR = 'GITHUB_REQUEST_ERROR',
  GITHUB_CLEAR_USERS = 'GITHUB_CLEAR_USERS',
}
